//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ToLuaFramework_MgrThreadWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ToLuaFramework.MgrThread), typeof(System.Object));
		L.RegFunction("Start", Start);
		L.RegFunction("Stop", Stop);
		L.RegFunction("AddExecuteFun", AddExecuteFun);
		L.RegFunction("New", _CreateToLuaFramework_MgrThread);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateToLuaFramework_MgrThread(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ToLuaFramework.MgrThread obj = new ToLuaFramework.MgrThread();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ToLuaFramework.MgrThread.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Start(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ToLuaFramework.MgrThread obj = (ToLuaFramework.MgrThread)ToLua.CheckObject(L, 1, typeof(ToLuaFramework.MgrThread));
			obj.Start();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Stop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ToLuaFramework.MgrThread obj = (ToLuaFramework.MgrThread)ToLua.CheckObject(L, 1, typeof(ToLuaFramework.MgrThread));
			obj.Stop();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddExecuteFun(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ToLuaFramework.MgrThread obj = (ToLuaFramework.MgrThread)ToLua.CheckObject(L, 1, typeof(ToLuaFramework.MgrThread));
			ToLuaFramework.ThreadEvent arg0 = (ToLuaFramework.ThreadEvent)ToLua.CheckObject(L, 2, typeof(ToLuaFramework.ThreadEvent));
			obj.AddExecuteFun(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

