//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_FontStyleWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.FontStyle));
		L.RegVar("Normal", get_Normal, null);
		L.RegVar("Bold", get_Bold, null);
		L.RegVar("Italic", get_Italic, null);
		L.RegVar("BoldAndItalic", get_BoldAndItalic, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Normal(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.FontStyle.Normal);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Bold(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.FontStyle.Bold);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Italic(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.FontStyle.Italic);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BoldAndItalic(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.FontStyle.BoldAndItalic);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.FontStyle o = (UnityEngine.FontStyle)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

